nav:
  - README.md
  - Actor.md
  - AffectedPercent.md
  - AllUsersDesire.md
  - AppVersionSel.md
  - Backlog.md
  - BacklogIssue.md
  - BlockStatus.md
  - Blockable.md
  - Bug.md
  - CodeDebtSeverity.md
  - Company.md
  - CompanyPerson.md
  - CoreRelease.md
  - Customer.md
  - CustomerHappiness.md
  - CustomerState.md
  - CustomerType.md
  - DeclType.md
  - Desire.md
  - DesireStrength.md
  - DevIssue.md
  - DevIssueType.md
  - DevIssuesStatusUpdater.md
  - DevProduct.md
  - DevService.md
  - DevTask.md
  - DevType.md
  - DocDecl.md
  - DocPackage.md
  - DocType.md
  - Effort.md
  - Epic.md
  - Estimation.md
  - Feature.md
  - FeatureStatus.md
  - IDesire.md
  - IIDesire.md
  - ISupportUnitItem.md
  - IUserStory.md
  - Incident.md
  - IntDesire.md
  - Issue.md
  - Issue.md
  - IssueSpuUsage.md
  - IssueStatus.md
  - Milestone.md
  - MilestoneStatus.md
  - ParamValue.md
  - Person.md
  - PersonalProject.md
  - Problem.md
  - ProductRole.md
  - ProductStatus.md
  - ProductType.md
  - RankedDesire.md
  - RankedMilestone.md
  - Roadmap.md
  - RoleStatus.md
  - Service.md
  - Severity.md
  - SpuNoChargeReason.md
  - Stability.md
  - SupportBulkMsg.md
  - SupportUnitMove.md
  - SupportUnitReg.md
  - SupportUnitWriteDown.md
  - SupportUnitWriteUp.md
  - TaskParam.md
  - TechTask.md
  - TechTaskType.md
  - Ticket.md
  - ToEstimateFix.md
  - TypeType.md
  - UniversalApp.md
  - Urgency.md
  - User.md
  - UserStory.md
