nav:
  - README.md
  - Actor.md
  - And.md
  - Company.md
  - CompanyGroup.md
  - Customer.md
  - IQr.md
  - IQueBlockParam.md
  - IQueRsp.md
  - IVisability.md
  - IVisabilityCombinator.md
  - IVisabilityOwner.md
  - Not.md
  - Or.md
  - Person.md
  - QrState.md
  - QrTemplate.md
  - QrVersion.md
  - QrVersionParam.md
  - QueBlockParam.md
  - QueBlockParamConst.md
  - QueChoiceOption.md
  - QueRspBlock.md
  - QueRspBlockItem.md
  - QueRspBool.md
  - QueRspChoice.md
  - QueRspChoiceOption.md
  - QueRspFiles.md
  - QueRspStaticText.md
  - QueRspStr.md
  - QueRspText.md
  - Questionnaire.md
  - ShowIfChosen.md
  - ShowIfNo.md
  - ShowIfNotChosen.md
  - ShowIfYes.md
  - TempateState.md
  - YesNo.md
