nav:
  - README.md
  - CategoryMargin.md
  - DDPThreshold.md
  - IBaseProduct.md
  - IMargin.md
  - IPriceFilterModOwner.md
  - IPriceMod.md
  - IPriceModOwner.md
  - IPriceRentDecorator.md
  - IPriceSalesRent.md
  - IProdFilter.md
  - IProdFilterOwner.md
  - IStaticPriceModel.md
  - KitItemPrice.md
  - KitModelRule.md
  - KitPrice.md
  - KitPriceModel.md
  - MarginPrice.md
  - MarginPriceModel.md
  - PriceList.md
  - PriceListProduct.md
  - PriceModApplier.md
  - PriceModDiscountFixed.md
  - PriceModDiscountPercent.md
  - PriceModDurDiscountPercent.md
  - PriceService.md
  - ProdFilterAnd.md
  - ProdFilterBrand.md
  - ProdFilterCategory.md
  - ProdFilterNot.md
  - ProdFilterOr.md
  - ProdFilterProd.md
  - ProdFilterTag.md
  - ProductCostSource.md
  - ProductMargin.md
  - SaleCampaign.md
  - SaleCampaignRule.md
