nav:
  - README.md
  - DeliveryOverdueState.md
  - DispatchState.md
  - FPathDates.md
  - FProductItems.md
  - FProductItemsInline.md
  - GoodAvailability.md
  - IAmountItem.md
  - IAmountQtyItem.md
  - IFProductItems.md
  - IIProdMoveItemIn.md
  - IIProdMoveItemOut.md
  - ILocation.md
  - IProdAmountQtyItem.md
  - IProdMove.md
  - IProdMoveIn.md
  - IProdMoveItem.md
  - IProdMoveItemIn.md
  - IProdMoveItemOut.md
  - IProdMoveOut.md
  - IProdMoveOut.md
  - IProdMovePath.md
  - IProdQtyItem.md
  - IProductItem.md
  - IRoute.md
  - ISuperProduct.md
  - InventoryWriteDown.md
  - InventoryWriteUp.md
  - PathState.md
  - ProdMoveState.md
  - RefProductItems.md
  - RefProductQty.md
  - StockCorrection.md
  - Stocktake.md
  - StocktakeItem.md
  - StocktakeType.md
  - SupplyRequirement.md
  - Transfer.md
  - TransferItem.md
  - Workspace.md
