nav:
  - README.md
  - Company.md
  - IXeroPaymentSaver.md
  - IncomingPayment.md
  - InitialSyncFinishedJob.md
  - InitialSyncState.md
  - Invoice.md
  - OurLegalEntity.md
  - OutgoingPayment.md
  - Person.md
  - PushAllContacsJob.md
  - PushContactJob.md
  - PushInvoiceJob.md
  - PushInvoiceRevisionJob.md
  - PushItemJob.md
  - QtyMeaning.md
  - RetrieveAccountsJob.md
  - RetrieveAssetsJob.md
  - RetrieveBankTransactionsJob.md
  - RetrieveBankTransfersJob.md
  - RetrieveContactsJob.md
  - RetrieveInvoicePaymentsJob.md
  - RetrieveInvoicesJob.md
  - RetrieveItemsJob.md
  - RetrieveMatchedItemsJob.md
  - RetrieveOneAssetJob.md
  - RetrieveOrganisationJob.md
  - RetrievePaymentJob.md
  - RetrievePaymentsJob.md
  - SyncFinishedJob.md
  - SyncMode.md
  - SyncUpdatesJob.md
  - XTestJob.md
  - XeroAccount.md
  - XeroAccountStatus.md
  - XeroAccountType.md
  - XeroAccountsResponse.md
  - XeroAddress.md
  - XeroAddressType.md
  - XeroAllocation.md
  - XeroAsset.md
  - XeroAssetsResponse.md
  - XeroBankAccount.md
  - XeroBankTransaction.md
  - XeroBankTransactionLineItem.md
  - XeroBankTransactionsResponse.md
  - XeroBankTransfer.md
  - XeroBankTransfersResponse.md
  - XeroBaseResponse.md
  - XeroBookDepreciationDetail.md
  - XeroBookDepreciationSettings.md
  - XeroContact.md
  - XeroContactPerson.md
  - XeroContactStatus.md
  - XeroContactsResponse.md
  - XeroCreditNote.md
  - XeroCreditNotePurchaseDiscountItem.md
  - XeroCreditNoteSalesDiscountItem.md
  - XeroCreditNoteStatus.md
  - XeroCreditNoteType.md
  - XeroCreditNotesResponse.md
  - XeroError.md
  - XeroErrorElement.md
  - XeroEvent.md
  - XeroIntegration.md
  - XeroIntegration.md
  - XeroIntegration.md
  - XeroIntegration.md
  - XeroInvoice.md
  - XeroInvoiceBase.md
  - XeroInvoiceLineItem.md
  - XeroInvoiceStatus.md
  - XeroInvoiceType.md
  - XeroInvoicesResponse.md
  - XeroItem.md
  - XeroItemPSDetails.md
  - XeroItemsResponse.md
  - XeroLineAmountTypes.md
  - XeroOrganisation.md
  - XeroOrganisationsResponse.md
  - XeroPagination.md
  - XeroPayment.md
  - XeroPaymentsResponse.md
  - XeroPhone.md
  - XeroPhoneType.md
  - XeroValidationError.md
  - XeroWebhookData.md
