nav:
  - README.md
  - AddressImportMapping.md
  - Company.md
  - Company.md
  - Company.md
  - ContactPersonImport.md
  - CounterpartyImportSchema.md
  - CpImportRelType.md
  - CpImportType.md
  - Customer.md
  - Entirety.md
  - GstRate.md
  - GstStatus.md
  - ICounterparty.md
  - ICustomer.md
  - IVendor.md
  - LegalEntity.md
  - LegalEntity.md
  - LegalEntity.md
  - LegalInfo.md
  - LocationImportMapping.md
  - OurCompany.md
  - OurPerson.md
  - Person.md
  - Person.md
  - Person.md
  - PersonIdDoc.md
  - PersonIdDocType.md
  - PhoneImport.md
  - Vendor.md
