nav:
  - README.md
  - MarketingProduct.md
  - MarketingProductGroup.md
  - Niche.md
  - ProductAdvantage.md
  - ProductNiche.md
  - PublicationStatus.md
  - Readiness.md
  - Screenshot.md
  - ScreenshotExternal.md
  - ScreenshotFlow2b.md
  - ScreenshotLocation.md
  - ScreenshotPage.md
  - ScreenshotStatus.md
  - ScreenshotTake.md
  - WebPage.md
