nav:
  - README.md
  - AreaOfBusiness.md
  - DownloadListingJob.md
  - DownloadListingsJob.md
  - FinTrType.md
  - FixedPrice.md
  - IBaseProduct.md
  - IPriceSales.md
  - ISubProduct.md
  - ListingRequest.md
  - ListingResponse.md
  - ListingResponseDetails.md
  - ListingStatus.md
  - ListingType.md
  - Margin.md
  - PayNowAccount.md
  - PayNowType.md
  - PaymentMethod.md
  - PercentOfCost.md
  - PercentOfSalesPrice.md
  - Pickup.md
  - PickupLocation.md
  - PingAccount.md
  - PostAnswerJob.md
  - ProductCategory.md
  - PushSalesOrderResponse.md
  - PushSalesOrderState.md
  - QuestionStatus.md
  - ReconTrademeMemberPayee.md
  - ReconTrademeMemberTransfer.md
  - ReconTrademePaynowTransfer.md
  - ReconTrademePingTransfer.md
  - ReconTrademePingTransferTo.md
  - RelistRequest.md
  - RetrieveListingStats.md
  - RetrieveQuestionsJob.md
  - RetrieveSoldItemsJob.md
  - SalesItem.md
  - ShippingCalculatorInputs.md
  - ShippingCharge.md
  - ShippingOption.md
  - ShippingOptionType.md
  - TrademeAccountContact.md
  - TrademeCategory.md
  - TrademeFinAccount.md
  - TrademeInitialDownload.md
  - TrademeIntegration.md
  - TrademeListing.md
  - TrademePrice.md
  - TrademeProductStatus.md
  - TrademeProductsPerformance.md
  - TrademePromotion.md
  - TrademeQuestion.md
  - TrademeShipping.md
  - UpdateCategoriesJob.md
  - UploadPhoto.md
  - UploadPhotoResponse.md
  - WeightOption.md
  - WithdrawRequest.md
