nav:
  - README.md
  - ApptState.md
  - ApptType.md
  - BookApi.md
  - BookPriceModel.md
  - BookPricePerson.md
  - BookProdPrice.md
  - BridalAppointment.md
  - BridalDetails.md
  - ConfirmResponse.md
  - Customer.md
  - DetailsRequest.md
  - DonnaMailTemplate.md
  - IOrderTerms.md
  - NewApptRequest.md
  - NewApptResponse.md
  - NotifyService.md
  - OpportunityDress.md
  - OpportunityState.md
  - OrderTerms.md
  - PerMeasurments.md
  - PeriodDataItem.md
  - PeriodsResponse.md
  - SalesOpportunity.md
  - SalesOrder.md
  - SelPeriodRequest.md
  - Workspace.md
