nav:
  - README.md
  - Company.md
  - CompanyPerson.md
  - Customer.md
  - DDRetShipping.md
  - DDShipping.md
  - DeliveryItem.md
  - DiscountDeliveryItem.md
  - DiscountItem.md
  - DlvRepeat.md
  - DlvRepeatService.md
  - DropShipDelivery.md
  - DropShipState.md
  - IDDShipping.md
  - IDlvProductItem.md
  - IDlvProgressItem.md
  - IOrderDlvItem.md
  - IPurchaseDelivery.md
  - IPurchaseItem.md
  - IPurchaseItemWithDelivery.md
  - IPurchaseProductItem.md
  - ISalesChannel.md
  - ISalesDelivery.md
  - ISalesDelivery.md
  - ISalesItem.md
  - ISalesItemWithDelivery.md
  - IShipping.md
  - LegalEntity.md
  - Order.md
  - OrderDeliveryState.md
  - OrderDlv.md
  - OrderItem.md
  - OrderProductItem.md
  - PDRetShipping.md
  - PDShipping.md
  - Person.md
  - PurchaseDelivery.md
  - PurchaseDiscountItem.md
  - PurchaseItem.md
  - PurchaseOrder.md
  - SDRetShipping.md
  - SDShipping.md
  - SalesChannel.md
  - SalesDelivery.md
  - SalesDiscountItem.md
  - SalesItem.md
  - SalesOrder.md
  - Shipping.md
  - Ticket.md
  - Transfer.md
  - User.md
  - Vendor.md
