nav:
  - README.md
  - Actor.md
  - AttributeType.md
  - Barcode.md
  - Brand.md
  - BrandAttr.md
  - Ceiling.md
  - CrossSell.md
  - Customer.md
  - DurPrice.md
  - ECommerceSyncStatus.md
  - ExpenseType.md
  - Floor.md
  - IAltUnits.md
  - IBarcode.md
  - IBaseProduct.md
  - IBaseProduct.md
  - IBaseProduct.md
  - IBasicKit.md
  - IBasicProduct.md
  - IBasicSubProduct.md
  - ICrossSell.md
  - IDynamicPriceModel.md
  - IIPriceModel.md
  - IIncomeType.md
  - IKit.md
  - IKitVariation.md
  - IPrice.md
  - IPriceLevel.md
  - IPriceModel.md
  - IPriceRent.md
  - IPriceSales.md
  - IProdUnit.md
  - IProduct.md
  - IProductAttr.md
  - IProductAttrTerm.md
  - IProductCategory.md
  - IProductImportSchema.md
  - IProductInv.md
  - IProductItem.md
  - IProductTag.md
  - IProductTaxonomy.md
  - IStaticPrice.md
  - IStaticPriceModel.md
  - IStaticPriceRent.md
  - IStaticPriceSales.md
  - ISubProduct.md
  - ISubProduct.md
  - ISubVariation.md
  - ISuperProduct.md
  - ISuperProduct.md
  - IVariableKit.md
  - IVariableSuperProduct.md
  - IVariation.md
  - IVendor.md
  - IVendor.md
  - IWeightSize.md
  - InventoryType.md
  - KitItem.md
  - PriceLevel.md
  - PriceLevelDefault.md
  - PriceModelNone.md
  - PriceModelState.md
  - PriceOrder.md
  - PriceOrderItem.md
  - PriceType.md
  - ProdRentStatus.md
  - ProdUQty.md
  - ProductAltUnit.md
  - ProductAttr.md
  - ProductAttrSelection.md
  - ProductAttrTerm.md
  - ProductCategory.md
  - ProductCost.md
  - ProductImportSchema.md
  - ProductImportType.md
  - ProductItem.md
  - ProductStatus.md
  - ProductTag.md
  - RentAmount.md
  - RevenueType.md
  - Round.md
  - Rounding.md
  - RuntimeAttributeExtension.md
  - SalesPrice.md
  - ShippingClass.md
  - Slot.md
  - StockType.md
  - TWeightSize.md
  - TWeightSizeOnly.md
  - TrackItems.md
  - UnitAttributeType.md
  - Workspace.md
  - Workspace.md
