nav:
  - README.md
  - AvailablePeriods.md
  - ContinuousPriceModel.md
  - ContinuousProductPrice.md
  - Customer.md
  - DurationSlot.md
  - IBaseProduct.md
  - IContinuousPriceModel.md
  - IContinuousProductPrice.md
  - IPriceRent.md
  - IRentItem.md
  - ISlottedPriceModel.md
  - ISlottedProductPrice.md
  - Invoice.md
  - LegalStructure.md
  - PurchaseRentItem.md
  - RentAvCalcItem.md
  - RentDeliveryItem.md
  - RentDuration.md
  - RentSlot.md
  - SalesBondItem.md
  - SalesOrder.md
  - SalesOrder.md
  - SalesRentItem.md
  - SlottedPriceModel.md
  - SlottedProductPrice.md
  - TRentPriceModel.md
  - TRentProductPrice.md
